### ISSUE TITLE
phpcs: Unable to locate phpcs, Please add phpcs to global path

### ISSUE THREAD

**Issue by joaomoreno** [ikappas/vscode-phpcs#14]
_From @ritayzy on July 8, 2016 6:50_
- VSCode Version: 1.3.0 (1.3.0)
- OS Version: 10.11.3 (15D21)
- vs plugin: [phpcs](https://github.com/ikappas/vscode-phpcs)

Steps to Reproduce:

when i open a `.php` file, the tips show that: 

![image](https://cloud.githubusercontent.com/assets/18484770/16679514/b913bb44-451a-11e6-81ec-829d036bbfce.png)

in my termianl, i input this `which phpcs`, show that:

![image](https://cloud.githubusercontent.com/assets/18484770/16679544/f51f616a-451a-11e6-85cc-afe2af2a169b.png)

Someone can help me. Thanks!

_Copied from original issue: Microsoft/vscode#8900_

**Comment by floridait** [comment]
Why is this closed? There is no fix for this yet. I have the same issue but it works when I start vscode from the command line.

**Comment by ritayzy** [comment]
There is the same problems at `eslint`,  I think it's bug's vscode, not `phpcs`。
Some people have solved it? Please help me，Thanks!

**Comment by joaomoreno** [comment]
Closing as duplicate of Microsoft/vscode#8434

**Comment by Wrenbjor** [comment]
@joaomoreno This is not a dupe of Microsoft/vscode#8434 Nothing in that thread fixes this issue. I am seeing the exact same problem with 1.19.1 on OSX. Is there a known fix or workaround?

**Comment by greenoss** [comment]
Im facing this problem too,
Would you mark this as open issue again @joaomoreno ?

**Comment by bahmanyaghoobi** [comment]
I have the same issue. Why is this closed?

**Comment by diegolaciar** [comment]
please post the fix before close the issue. I have the same issue.

**Comment by MrAmbiG** [comment]
Installing the composer globally fixed it for me.
https://getcomposer.org/doc/00-intro.md#globally

**Comment by mobayen** [comment]
This one worked for me:

https://stackoverflow.com/questions/47174009/visual-code-studio-unable-to-locate-phpcs

1- Go to extensions and install the plugin...."phpcs".
2- Search for the extension if you had install it.
3- Disable the extension.

**Comment by ikappas** [comment]
I just released vscode-phpcs 1.0.0 which supports the VSCode 1.20+ and includes many enhancements most notable of which are:

1. multi root support
2. lint as you type support
3. automatic configuration search support
4. ability to set phpcs.executablePath
5. ability to set phpcs.showWarnings
7. ability to set phpcs.showSources
8. ability to set phpcs.composerJsonPath to something other that workspaceRoot/composer.json
9. ability to enable phpcs.trace.server with messages or verbose option for tracing errors.

I would like to give my thanks to all the people that helped track down issues in the previous betas and hope the new features help you get things done easier.
On that note, I am closing this issue to properly track any new issues in the new release. If you find this issue persists or any other issue please feel free to open a new ticket for v.1.0.0.

**Comment by cerzzwiz** [comment]
Hi guys if someone still needs help about this "Unable to locate phpcs ..." error message try this: you just need to install phpcs globally via Composer.
1- Install Composer from https://getcomposer.org/download/ if you don't have it,
2- After Composer is installed, open a command prompt wherever you want and run this command =>

composer global require squizlabs/php_codesniffer

**Comment by briandrolet** [comment]
thank you for the fixes @ikappas , it's very much appreciated!

**Comment by karson** [comment]
i installed phpcs global via composer , but error persists i had to insert executable phat manually. i'm using ubuntu 16.10

**Comment by ros-financial-com** [comment]
In Fedora 27, I solved the problem by installing php-pear-PHP-CodeSniffer-3.2.3-1.fc27.noarch. This should be true for RHEL, too.
I guess a similar package is available for .deb based Linuxes, too.

**Comment by kakasal** [comment]
This is still an un-resolved issue.

**Comment by romankua** [comment]
I'm having the issue on macOS High Sierra.

Installed all according to instruction:
1. Installed composer globally (Composer version 1.6.3).
2. composer global require squizlabs/php_codesniffer.
3. Installed phpcs VSC extension.

**Comment by oviniciusfeitosa** [comment]
Try to follow this steps:

- Installing globally PHPCS
```
composer global require squizlabs/php_codesniffer
```

- Know yout $path
```
echo $path
```

- Add line below into your ```~/.zshrc``` ou ```~/.bashrc```
```
export PATH="/home/$USER/.config/composer/vendor/bin:$PATH"
```

**Comment by markfullmer** [comment]
In your VS Code "User Settings" ("Preferences"), add:

```
    "phpcs.executablePath":"/path/to/phpcs"
```

See item 4, above, from the maintainer: https://github.com/ikappas/vscode-phpcs/issues/14#issuecomment-367287572

**Comment by bobbyConnxus** [comment]
On Ubuntu 17.10 sudo apt install php-codesniffer resolved the issue for me.

**Comment by creativestate** [comment]
On Windows:

- Install [Composer](https://getcomposer.org/download/)
- Install PHP_CodeSniffer via Composer using "composer global require squizlabs/php_codesniffer" in the command prompt for a system wide install

Details are listed on the https://marketplace.visualstudio.com/items?itemName=ikappas.phpcs page.

**Comment by goseesomething** [comment]
I have the same problem but using the method offered by cerzzwiz then the error message never come again~

**Comment by itgconsulting** [comment]
sudo apt install php-codesniffer

**Comment by rgfpy** [comment]
In Windows i added these lines config:

`"phpcs.enable": true,`
`"phpcs.autoConfigSearch": true,`
`//comment or remove the item "phpcs.executablePath": "",`
`"php.validate.executablePath": "C:/wamp64/bin/php/php7.0.32/php.exe",`

**Comment by egirlasm** [comment]
in user workspace setting(not user setting)
`
"phpcs.executablePath": "/Users/egirlasm/.composer/vendor/bin/phpcs"
`
finally must be add phpcs in the end

**Comment by jel111** [comment]
I have tried all the above but things didn't work until I went into settings and added the actual path to the:
Executable Path - Optional. The path to the phpcs executable.
Mine happens to : /Users/macuser/vendor/squizlabs/php_codesniffer/bin

I don't know why because I ran the command to change this as described above but that didn't happen. Let me know what I did wrong here, please. If you need more info let me know. Thanks!

**Comment by TheHunterDog** [comment]
I am still having this problem
