### ISSUE TITLE
Proper way to setup this?

### ISSUE THREAD

**Issue by LittleHamster** [ikappas/vscode-phpcs#96]
I am not sure what I am doing wrong but I can't get this plugin to work. I keep getting error messages:

![image](https://user-images.githubusercontent.com/10330481/36574806-6c3e14a2-1815-11e8-82b2-344d06334404.png)

I have setup PHPCS with PhpStorm and it works perfectly but  I can't get it working for VSCODE with this plugin. I followed all the instructions, 

```
php -v
PHP 7.1.7 (cli) (built: Jul 15 2017 18:08:09) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

reinstalled PHPCS with pear

```
downloading PHP_CodeSniffer-3.2.3.tgz ...
Starting to download PHP_CodeSniffer-3.2.3.tgz (560,524 bytes)
.................................................................................................................done: 560,524 bytes
install ok: channel://pear.php.net/PHP_CodeSniffer-3.2.3

```

but nothing. 
I can't get this to work, any idea what is happening?

**Comment by ikappas** [comment]
@LittleHamster Did you try running 
```bash
/usr/local/bin/phpcs --report=json -1 --encoding=UTF-8 --standard=WordPress /path/to/your/php/file
```

**Comment by LittleHamster** [comment]
@ikappas 
thanks for your response, 
this is the output of your command:

```
sh: line 1:  1684 Illegal instruction: 4  stty size 2>&1
ERROR: option "-1" not known

Run "phpcs --help" for usage information
```

so if I remove `-1` I get a message like: 
```
{"totals":{"errors":119,"warnings":48,"fixable":93},"file...
```

**Comment by ikappas** [comment]
@LittleHamster Can you check whether "phpcs.autoConfigSearch": "false" changes the error?

**Comment by LittleHamster** [comment]
@ikappas 
sadly no :(
still the same error message

**Comment by ikappas** [comment]
@LittleHamster The unknown error is thrown when PHP_CodeSniffer returns an error in stderr and is not one of PHP error or exception. That means that the command to execute phpcs fails for some reason.  

Some users have reported that you need to upgrade your php to >=7.1.13 or >=7.2.1 To avoid bug fixed by php in 7.1.x || 7.2.x.

**Comment by LittleHamster** [comment]
@ikappas 
so I updated the php
```
 php -v
PHP 7.2.2 (cli) (built: Feb  1 2018 13:23:34) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.2, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
Dolatabadi@connected ~ $ 
```

but still have the same issue 
PHP_CodeSniffer works on PhpStorm so not sure why it doesnt work here

**Comment by ikappas** [comment]
@LittleHamster Are you on a Linux or Mac ? Also have you tried installing phpcs via composer globally?

**Comment by ghost** [comment]
@ikappas 
I am on a Mac. yes, I tried to install phpcs via composer globally, but still no luch

**Comment by sethstha** [comment]
@LittleHamster I had the same issue and couldn't get phpcs to work. I will give you clear instruction here.

First, open the project on vscode and open inbuilt terminal.

Install phpcs
`composer require squizlabs/php_codesniffer`

Install wpcs
`composer require wp-coding-standards/wpcs`

This plugin will automatically load phpcs standards found
`composer require dealerdirect/phpcodesniffer-composer-installer`

Now try checking if phpcs standards are installed or not by typing 
`vendor/bin/phpcs -i`

If standards are showing and still you cannot get it to work, try linting a file through command using `--standard="WordPress"` and if it throws some error delete your phpcs installed locally and globally. And follow the above instruction again.

**Comment by ghost** [comment]
@sethstha 
I followed your instructions and for this command I get the following output:
```
vendor/bin/phpcs -i
sh: line 1: 40564 Illegal instruction: 4  stty size 2>&1
The installed coding standards are PEAR, Zend, PSR2, MySource, Squiz, PSR1, WordPress-VIP, WordPress, WordPress-Extra, WordPress-Docs and WordPress-Core
```

but I still get this error: 
![image](https://user-images.githubusercontent.com/10330481/36956140-b0ddb5f8-1ffa-11e8-8349-30ea675c9889.png)

here are my settings: 
```
    .....
    "phpcs.standard": "WordPress",
    "phpcs.autoConfigSearch": false
```

**Comment by kevinfiol** [comment]
This extension has just straight up stopped working for me. Even tried using a global installation of phpcs. No more codesniffing for me it seems. I'm using a local Composer installation, located in /vendor/.

Here are some screenshots.
![1](https://user-images.githubusercontent.com/4752973/37159525-23e4be98-22bc-11e8-84e9-af76734a53da.png)
![2](https://user-images.githubusercontent.com/4752973/37159526-23f99872-22bc-11e8-8b1c-09cb0e06c193.png)
![3](https://user-images.githubusercontent.com/4752973/37159527-240cc6cc-22bc-11e8-992c-8c99750fb66b.png)

**Comment by ikappas** [comment]
@kevinfiol On first screenshot you are viewing the output of PHP Intellisense... vscode-phpcs has it own output under **PHP Code Sniffer** when phpcs.trace.server is enabled. You can also use "phpcs.xml" in your phpcs.standard which is relative to project root. Last thing I noticed you are using the <file>.</file> in your phpcs.xml which I have seen causing some trouble. Can you comment that out and check whether your situation changes?

**Comment by ikappas** [comment]
@kevinfiol You can also set phpcs.executablePath in workspace/project settings (not user) to "vendor/bin/phpcs"

**Comment by kevinfiol** [comment]
No change on my end. I tried using `vendor/bin/phpcs` and `vendor/bin/phpcs.bat`. No luck with either. I also do not see any option for PHP Code Sniffer in my Output panel.

![5](https://user-images.githubusercontent.com/4752973/37165432-9c1e2fbc-22ca-11e8-8d60-41212477b982.png)
![4](https://user-images.githubusercontent.com/4752973/37165436-9e61ab28-22ca-11e8-9449-72f24b79aad1.png)

**Comment by ikappas** [comment]
@kevinfiol is the php executable C:\bin\easy\eds-binaries\php\php713v.... registered in you Windows PATH in your environment variables under System Advanced Preferences (see https://superuser.com/questions/949560/how-do-i-set-system-environment-variables-in-windows-10 )

**Comment by kevinfiol** [comment]
Yes.
![jewswb](https://user-images.githubusercontent.com/4752973/37173927-04ae92b6-22e3-11e8-890b-33e7289cfa40.png)

**Comment by kevinfiol** [comment]
Update: I've since installed version 1.0.3 of the extension (as that was the last version wherein i did not have problems) and it is working again.

**Comment by ikappas** [comment]
@kevinfiol The latest version of the extension is 1.0.5

**Comment by kevinfiol** [comment]
@ikappas I realize this. It was not working while I was on 1.0.5. So I reverted back to 1.0.3, and it is working now.

**Comment by ikappas** [comment]
@kevinfiol I realized what you did after posting :) Do you think you can clone the repo and debug this issue in windows so you can help me get some insight on this?

**Comment by kevinfiol** [comment]
@ikappas Sure, I will look into this more tomorrow. :) Thanks.

**Comment by ikappas** [comment]
@kevinfiol Thank you in advance 👍

**Comment by ikappas** [comment]
@kevinfiol Did you have a chance to debug?

**Comment by kevinfiol** [comment]
@ikappas Sorry, got swamped in work. I've attempted to debug, but keep hitting this issue immediately upon starting to debug:

![rxqeto](https://user-images.githubusercontent.com/4752973/37417795-8bb9bc10-2787-11e8-8b40-c02bc09f89a3.png)

I've replicated my environment at my home PC (using the plugin version 1.0.5), and found that the plugin works fine!! We do have some funky firewalls and other anti-malware measures here at work, so I imagine the issue might lay there, but I am unsure at this point.

**Comment by glen-84** [comment]
The extension has also stopped working for me. It doesn't seem to load at all.

* Windows 10
* VS Code 1.21.1
* PHP_CodeSniffer version 2.7.1 (installed globally with Composer)

**Comment by ikappas** [comment]
@kevinfiol Sorry for the late response but this is not a firewall issue. There is a 10 sec timeout from task launch within which you need to open a php file to trigger the loading of plugin.  If you run into this msgbox again you can ignore it and launch a second debug session with 'Attach to Server' task - provided you have the Extension Host running with an opened a php file first.

**Comment by ghost** [comment]
@ikappas 
any feedback about my issue, kevin hijacked my issue :( 
I am still having the issue
